# Удалите атрибут `version` из docker-compose.yml и попробуйте следующее:

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "3000:3000"
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      - CONFIG_PATH=/root/configs/config.yaml
    restart: on-failure

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pvz_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
