DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS receptions;
DROP TABLE IF EXISTS pvzs;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS reception_status;
DROP TYPE IF EXISTS product_type;
DROP TYPE IF EXISTS city_type;
DROP TYPE IF EXISTS user_role;
