server:
  http_port: "8081"
  grpc_port: "3001"
  metrics_port: "9001"
  read_timeout: 10s
  write_timeout: 10s

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "test_avito_pvz"
  sslmode: "disable"

auth:
  jwt_secret: "test_jwt_secret_key"
  jwt_expiration: 24h

log:
  level: "debug"
